### ISSUE TITLE
Avatar File is Required issue

### ISSUE THREAD

**Issue by Talhaayub1** [hiteshchoudhary/chai-backend#34]
I checked and everything is working, and when I sent a request using Postman,  this avatar file issue occurred. How can I resolve this issue?
<img width="892" alt="Screenshot 2023-12-23 220508" src="https://github.com/hiteshchoudhary/chai-backend/assets/103215272/3d7687f1-fa7b-41ea-bac0-e32da61bbe14">

**Comment by nirajchaurasiya** [comment]
Hey, I think the condition you are writing for the avatar file is wrong.

Check the if condition once.

Additionally, you can provide us with your repo URL.

**Comment by anishudupa** [comment]
check for middleware once and check if you are accessing the file correctly (req.files not req.file)
check here - https://github.com/expressjs/multer
or else provide your source code repo link

**Comment by Talhaayub1** [comment]
Can you clone my repo? or did I send the link? because I checked everything but the avatar file is still throwing issue

**Comment by Talhaayub1** [comment]
Can you clone my repo? or did I send the link? because I checked everything but the avatar file is still throwing issue

**Comment by Talhaayub1** [comment]
Can you clone my repo? or did I send the link? because I checked everything but the avatar file is still throwing issue

**Comment by nirajchaurasiya** [comment]
Yeah, you can send us the repo URL.

**Comment by Talhaayub1** [comment]
https://github.com/Talhaayub1/backend.git this is the repo!!!!

**Comment by nirajchaurasiya** [comment]
I will update you after checking.

**Comment by nirajchaurasiya** [comment]
Can you provide me the .env.sample file with only names of variables?

**Comment by Talhaayub1** [comment]
i didn't create .env.sample i just create .env

**Comment by nirajchaurasiya** [comment]
So, you have to create it or just provide me with a screenshot of the variable names.

**Comment by Talhaayub1** [comment]
i provide the screenshot!! i have all varibles in .env

**Comment by Talhaayub1** [comment]
<img width="443" alt="Screenshot 2023-12-24 191528" src="https://github.com/hiteshchoudhary/chai-backend/assets/103215272/8c542257-fca0-4098-bd22-54f5b2dd356b">
check this

**Comment by nirajchaurasiya** [comment]
Hmm, I see.
Everything is fine.
Can you check the keys of Cloudinary once?
Because the problem comes with uploading the file to Cloudinary.

**Comment by Talhaayub1** [comment]
check this when i create account on cloudinary so node js give me this api_secret: '***************************' as it is i copy to .env?

**Comment by nirajchaurasiya** [comment]
Yeah, just a silly mistake, man.
Check this video👇

https://github.com/hiteshchoudhary/chai-backend/assets/116571542/4660e427-706b-4ec5-86cc-10a3e1161747

**Comment by nirajchaurasiya** [comment]
And, then you can see your api_secret.

**Comment by Talhaayub1** [comment]
got it man!! Thanks For this, resolve the issue 🙌❤️

**Comment by nirajchaurasiya** [comment]
Glad to help❤️

**Comment by AdityaHeree** [comment]
thanks for your efforts . i do all this changes i cant fix the ploblem. i think i some line previously

**Comment by itzmeimran** [comment]
Here dont use GET method instead use POST method as you are supposed to send files. Hope this ll help you fix error

**Comment by shobitkhatri05** [comment]
Hello Brother @nirajchaurasiya  I also the face same issue avatar is required Can you clone my repo? or did I send the link? because I checked everything but the avatar file is still throwing issue

**Comment by RAMraghuram** [comment]
# Avatar is required issues

The issue is within the `cloudinary.js` file. When we are unlinking the local file path before sending the response, we should first check if the local file exists or not. As it is happening asynchronously, there is a chance that it is unlinking before all other tasks are completed. The best option would be to check if `localFilePath` exists, and then unlink it using the following code:

```
fs.existsSync(localFilePath) && fs.unlinkSync(localFilePath);
```

This is the final version: 

```
import { v2 as cloudinary } from "cloudinary";
import fs from "fs";

cloudinary.config({
  cloud_name: process.env.CLOUDINARY_CLOUD_NAME,
  api_key: process.env.CLOUDINARY_API_KEY,
  api_secret: process.env.CLOUDINARY_API_SECRET,
});

const uploadCloudinary = async (localFilePath) => {
  try {
    if (!localFilePath) return null;
    console.log("localFilePath", localFilePath);
    // upload file to cloudinary
    const response = await cloudinary.uploader.upload(localFilePath, {
      resource_type: "auto",
    });
    // file has been uploaded
    // console.log("File uploaded to cloudinary", response.url);
    fs.existsSync(localFilePath) && fs.unlinkSync(localFilePath);
    // console.log("response", response);
    return response;
  } catch (error) {
    fs.existsSync(localFilePath) && fs.unlinkSync(localFilePath); // remove file from local storage if cloudinary upload fails
    return null;
  }
};

export { uploadCloudinary };

```

**Comment by akashsahaks** [comment]
Great to hear this, I will verify this!!

**Comment by snehitshh** [comment]
i am having the same issue can someone please help, i tried the above methods none of them worked :(

**Comment by harshgarg007** [comment]
> # Avatar is required issues
> The issue is within the `cloudinary.js` file. When we are unlinking the local file path before sending the response, we should first check if the local file exists or not. As it is happening asynchronously, there is a chance that it is unlinking before all other tasks are completed. The best option would be to check if `localFilePath` exists, and then unlink it using the following code:
> 
> ```
> fs.existsSync(localFilePath) && fs.unlinkSync(localFilePath);
> ```
> 
> This is the final version:
> 
> ```
> import { v2 as cloudinary } from "cloudinary";
> import fs from "fs";
> 
> cloudinary.config({
>   cloud_name: process.env.CLOUDINARY_CLOUD_NAME,
>   api_key: process.env.CLOUDINARY_API_KEY,
>   api_secret: process.env.CLOUDINARY_API_SECRET,
> });
> 
> const uploadCloudinary = async (localFilePath) => {
>   try {
>     if (!localFilePath) return null;
>     console.log("localFilePath", localFilePath);
>     // upload file to cloudinary
>     const response = await cloudinary.uploader.upload(localFilePath, {
>       resource_type: "auto",
>     });
>     // file has been uploaded
>     // console.log("File uploaded to cloudinary", response.url);
>     fs.existsSync(localFilePath) && fs.unlinkSync(localFilePath);
>     // console.log("response", response);
>     return response;
>   } catch (error) {
>     fs.existsSync(localFilePath) && fs.unlinkSync(localFilePath); // remove file from local storage if cloudinary upload fails
>     return null;
>   }
> };
> 
> export { uploadCloudinary };
> ```

this is not working bro 😭😭
error in vs code terminal :-
MongoDB Connected !! DB HOST: localhost
😎 Server listening on 👉 8000
email: h1@.com
public\temp\pic.jpeg
Error: Avatar is required
    at file:///D:/chaibackend/src/controllers/user.controller.js:47:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by AmarNarayanDwivedi** [comment]
i am stuck from a month in this issue please help me guys 
thsi is my repo link : https://github.com/AmarNarayanDwivedi/Backend-Project/tree/main
![Screenshot 2024-06-25 161203](https://github.com/hiteshchoudhary/chai-backend/assets/119877633/c6efd415-7f71-4781-bf3a-630aa56b6b56)

**Comment by harshgarg007** [comment]
const avatarLocalPath = req.files?.avatar ?.[0]?.path;
Use this

**Comment by AmarNarayanDwivedi** [comment]
same error no effect

**Comment by Talhaayubkhan** [comment]
can you copy necessary things from cloudinary???? means what we store in .env file to send avatar to cloudinary?? try to update those

**Comment by AmarNarayanDwivedi** [comment]
i didn't understand what you are telling about 

is you are suggesting to change Cloudinary keys

**Comment by Talhaayubkhan** [comment]
CLOUDINARY_CLOUD_NAME= dqypjs4tl
CLOUDINARY_API_KEY= 225719471113895
CLOUDINARY_API_SECRET= hxjkdbdBSSHk68jdhh3dd35h4kj
rerecheck these keys

and make sure you correctly write multer middleware

**Comment by Sagar-1103** [comment]
the problem is we are not actually using the cloudinary.config part , to fix it make sure u put the config part inside the function like below :


![cloudinaryconfig](https://github.com/hiteshchoudhary/chai-backend/assets/116627861/37dc73a7-6976-4e6d-80cf-c97e170436d3)



and if you are getting this error - TypeError: Cannot read properties of undefined (reading '0')  
then just use this in your user controller

`const avatarLocalPath = await req?.files?.avatar?.[0]?.path;`
`const coverImageLocalPath = await req?.files?.coverImage?.[0]?.path;`
 
 we are getting this error because when a file is not uploaded then avatar[0] doesnt make any sense

**Comment by sainideepanshu** [comment]
Just verify your CLOUDINARY_API_SECRET in .env file again.

**Comment by pranjal13sam** [comment]
Hi neeraj,
![Screenshot (1)](https://github.com/user-attachments/assets/4c2466a5-6f66-4b7d-bea6-d820821adbfd)


above i have attached the screenshot of my error. i am getting the 
same error of avatar file is required although i followed all your steps but it din't worked so can you please help me out here.

**Comment by pranjal13sam** [comment]
@nirajchaurasiya

**Comment by pranjal13sam** [comment]
![Screenshot (2)](https://github.com/user-attachments/assets/15adc67e-fdf2-47b4-9d75-414b115d63d0)
![Screenshot (3)](https://github.com/user-attachments/assets/3dddf73d-9ff5-43a0-a719-4391628e2923)
these are my clodinary and env screenshots

**Comment by RohitBCA456** [comment]
Avatar Local Path: public\temp\Screenshot 2025-01-04 193539.png
Uploading file to Cloudinary: public\temp\Screenshot 2025-01-04 193539.png
Error uploading to Cloudinary: {
  error: { message: 'Request Timeout', http_code: 499, name: 'TimeoutError' }
}
Uploading file to Cloudinary: public\temp\Screenshot 2024-12-08 181724.png
Error uploading to Cloudinary: {
  error: { message: 'Request Timeout', http_code: 499, name: 'TimeoutError' }
}
Error: Avatar file is required
    at file:///C:/Users/hp/OneDrive/Desktop/chai%20aur%20backend/src/controllers/user.controller.js:64:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
### 

> please help me in solving this error

**Comment by hannibal1631** [comment]
I know anyone new still must be facing this issue. Here's what fixed it for me.
So till now meaning video no. 14, if you've followed the video carefully, your code is fine. Check the camelcase (fullName) variables carefully. If everything is exactly like how Hitesh Sir did in the previous videos don't worry. Check your cloudinary envs.
For me and many other i'm sure the main culprit was the CLOUDINARY_CLOUD_NAME. If you've named your cloud something specific (like superman) but you've copied the alphanumeric value from the node.js example file (a2sdf5g3asd4efdsae8), change that alphanumeric name with your cloud name. This fixed this issue for me right away.
Hope this helps, cause this is pretty hard to miss. Most people will only look at the api_key or security_key.

**Comment by urbruder** [comment]
Can anyone please tell me that when the avatar image is successfully uploaded on cloudinary whether it get sdeleted from the temp folder or not. In my case, it remains in the temp folder

**Comment by bk-suranjan** [comment]
if you use fs.unlink (or fs.unlinkSync) on a file, Node.js will automatically delete that file from your server. so make sure to include this when the image uploaded
