### ISSUE TITLE
Can not get the properties of undefined when register user in posan 

### ISSUE THREAD

**Issue by 123akkhi** [hiteshchoudhary/chai-backend#48]
When reister user postman itsays canot read properties of undefined

**Comment by 123akkhi** [comment]
Uploading VID20240104114446.mp4…

**Comment by 123akkhi** [comment]
Facing this error I cross check coded middleware and routes but everything fone

**Comment by Sreejit-Sengupto** [comment]
Could you share the form data or RAW JSON data

**Comment by ElbinBinil** [comment]
Even i have the same issue

**Comment by ganeswar07** [comment]
Send middleware code

**Comment by Jashk120** [comment]
Same issue here, I think its issue related to postman, cause having same issue with register(worked find yesterday and got user created in DB), but not getting Type Error even when register and login

code for register: `// step 1
    const {email, password, username, fullname } = req.body
    
      
        
    
    //Step 2
    if (
        [fullname, email, username, password].some((field) => field?.trim() === "")
        ) { //checking if any of the field is empyty if yes return true
        throw new ApiError(400, "All Fields are Required")
    }
    //step 3
    const existingUser = await User.findOne({
        $or:[{ username } , { email }]
    })
    if (existingUser){
        throw new ApiError(409, "User Already exist")
    }
    //Step 4
    const avatarLocaPath = req.files?.avatar[0]?.path;  //always use ?(optionl, maybe we got file maybe not)
    const coverImageLocalPath =req.files?.coverImage[0]?.path
    
    // let coverImageLocalPath;
    // if (req.files && Array.isArray(req.files.coverImage) && req.files.coverImage.length > 0) {
    //     coverImageLocalPath = req.files.coverImage[0].path
    // }

    //checking if avatar is uploaded cause that is necessary
    if (!avatarLocaPath) {
        throw new ApiError(400, "avatar file is required")
    }
    console.log(avatarLocaPath,coverImageLocalPath);
    // Step 5 uploading
    const avatar = await uploadOnCloudinary(avatarLocaPath)
    const coverImage = await uploadOnCloudinary (coverImageLocalPath)

    // checking if avatar is present or it will tear the database
    if (!avatar) {
        throw new ApiError(400, "avatar file is required")
    }

    //Step 6 making entry in database
    const user = await User.create({
        fullname,
        avatar: avatar.url,
        coverImage: coverImage?.url || "", // we have checked that avatar is present but havent checked CoverImage, so if it is not present, keep the field empty
        email,
        password,
        username: username.toLowerCase()
    })
    //checking if user is successfully created
    //Step 7 removing password and refreshtoken field from response using . select
    const createdUser = await User.findById(user._id).select(
        "-password -refreshToken"
    )
    if(!createdUser){
        throw new ApiError(500,"Somethin Went Wrong While Regestiring the user")
    }

return res.status(201).json(
    new ApiResponse(200, createdUser, "User Registered Successfully")
)
})`

**Comment by ganeswar07** [comment]
What type error did you get. Share full error message

**Comment by Jashk120** [comment]
> What type error did you get. Share full error message
In Terminal
```
 TypeError: Cannot read properties of undefined (reading '0')
[0]     at file:///F:/Work/Information/WEB%20DEVELOPMENT/00.Projects/YouTube%20Backend/src/controllers/user.controller.js:58:45
[0]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

In Postman:
```
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>Error</title>
</head>

<body>
    <pre>TypeError: Cannot read properties of undefined (reading &#39;0&#39;)<br> &nbsp; &nbsp;at file:///F:/Work/Information/WEB%20DEVELOPMENT/00.Projects/YouTube%20Backend/src/controllers/user.controller.js:58:45<br> &nbsp; &nbsp;at process.processTicksAndRejections (node:internal/process/task_queues:95:5)</pre>
</body>

</html>
```

**Comment by ganeswar07** [comment]
Console req.body and send it

**Comment by Jashk120** [comment]
> Console req.body and send it

[Object: null prototype] {
[0]   email: 'jayeshgmail',
[0]   password: 'Jayesh123',
[0]   username: 'Jayesh',
[0]   fullname: 'Jayesh'
[0] }

**Comment by ganeswar07** [comment]
Now req.files

**Comment by Jashk120** [comment]
> Now Console req.files. send ss of login route where you setup multer middleware.

[Object: null prototype] {}
[0] TypeError: Cannot read properties of undefined (reading '0')
[0]     at file:///F:/Work/Information/WEB%20DEVELOPMENT/00.Projects/YouTube%20Backend/src/controllers/user.controller.js:59:45
[0]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by Jashk120** [comment]
> Now Console req.files. send ss of login route where you setup multer middleware.

const router = Router()
router.route("/register").post(
    upload.fields([
        {
            name: "avatar",
            maxCount: 1
        },
        {
            name: "coverImage",
            maxCount:1
        }
    ]),
    registerUser
    )

**Comment by Jashk120** [comment]
> Now Console req.files. send ss of login route where you setup multer middleware.

also multer is only used in register route

**Comment by SWAGATSWAROOP** [comment]
Its working with raw json data but the form is not working
Send data in form json working otherwise not

**Comment by Jashk120** [comment]
> Its working with raw json data but the form is not working Send data in form json working otherwise not

thought so, the error is with postman

**Comment by ganeswar07** [comment]
Send avatar and coverImage through postman and console req.files.and avatarlocalimage and coverimagelocal file .

**Comment by Jashk120** [comment]
> Send avatar and coverImage through postman and console req.files.and avatarlocalimage and coverimagelocal file . And share your repo link

https://github.com/Jashk120/Backend

**Comment by ganeswar07** [comment]
Try this 

const avatarLocalPath = req?.files?.avatar[0].path;

    if (!avatarLocalPath) {
      throw new ApiError(400, "Please upload an avatar");
    }

    let coverImageLocalPath;
    if (
      req.files &&
      Array.isArray(req.files.coverImage) &&
      req.files.coverImage.length > 0
    ) {
      coverImageLocalPath = req.files.coverImage[0].path;
    }

**Comment by Jashk120** [comment]
> Try this
> 
> const avatarLocalPath = req?.files?.avatar[0].path;
> 
> ```
> if (!avatarLocalPath) {
>   throw new ApiError(400, "Please upload an avatar");
> }
> 
> let coverImageLocalPath;
> if (
>   req.files &&
>   Array.isArray(req.files.coverImage) &&
>   req.files.coverImage.length > 0
> ) {
>   coverImageLocalPath = req.files.coverImage[0].path;
> } 
> ```

still same issue

**Comment by ganeswar07** [comment]
used this format 
```  
const videoLocalFile = req?.files?.videoFile;
  if (!(videoLocalFile && videoLocalFile[0].path)) {
    throw new ApiError(400, "Video file is required");
  }

**Comment by Sreejit-Sengupto** [comment]
I think your files are not being read. Have you tried using some other images?

**Comment by 123akkhi** [comment]
![Uploading 1704954582850476155473813435414.jpg…]()

**Comment by 123akkhi** [comment]
![Uploading 17049546145242432777346564809091.jpg…]()

**Comment by 123akkhi** [comment]
Now it says Avatar is required
